# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 2020 T1 Reproducibility Challenge
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/rrsg2020/book  # Online location of your book
  path_to_book: source  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

only_build_toc_files: true
